services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"  # Expose the NATS client port
      - "6222:6222"  # Expose the NATS cluster port
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks:
      - app-network

  nestjs-app:
    build: .
    depends_on:
      - nats
    environment:
      - NATS_SERVER=nats://nats:4222
    networks:
      - app-network
    ports:
      - "3002:3000"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  sms-service:
    build: .
    depends_on:
      - nats
    environment:
    - NATS_SERVER=nats://nats:4222
    ports:
      - "3003:3000"  
    networks:
      - app-network
    

  email-service:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NATS_SERVER=nats://nats:4222
    depends_on:
      - nats
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  user-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NATS_SERVER=nats://nats:4222
    depends_on:
      - nats
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
      

networks:
  app-network:
    driver: bridge