

# services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest

  # email-service:
  #   build: .
  #   ports:
  #     - "4000:3000"
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672



services:
  nats:
    image: nats:latest
    ports:
      - '4222:4222'
      - '8222:8222'
    networks:
      - app-network

  nestjs-app:
    build: .
    depends_on:
      - nats
    environment:
      NATS_SERVER: 'nats://nats:4222'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge