

# services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest

  # email-service:
  #   build: .
  #   ports:
  #     - "4000:3000"
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"  # Expose the NATS client port
      - "6222:6222"  # Expose the NATS cluster port
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks:
      - app-network

  nestjs-app:
    build: .
    depends_on:
      - nats
    environment:
      - NATS_SERVER=nats://nats:4222
    networks:
      - app-network
    ports:
      - "3001:3000"

  email-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NATS_SERVER=nats://nats:4222
    depends_on:
      - nats
    networks:
      - app-network

networks:
  app-network:
    driver: bridge